export const PRODUCT_NAME_MIN_LENGTH = 2;
export const PRODUCT_NAME_MAX_LENGTH = 160;
export const PRODUCT_SLUG_MIN_LENGTH = 2;
export const PRODUCT_SLUG_MAX_LENGTH = 120;
export const PRODUCT_SUMMARY_MAX_LENGTH = 280;
export const PRODUCT_DESCRIPTION_MIN_LENGTH = 2;
export const PRODUCT_DESCRIPTION_MAX_LENGTH = 8_000;
export const PRODUCT_VARIANT_NAME_MAX_LENGTH = 255;
export const PRODUCT_VARIANT_SKU_MAX_LENGTH = 64;
export const PRODUCT_VARIANT_MAX_STOCK = 10_000_000;
export const PRODUCT_VARIANT_LOW_STOCK_THRESHOLD = 10;
export const PRODUCT_VARIANT_MAX_OPTION_ITEMS = 32;
export const PRODUCT_VARIANT_OPTION_NAME_MAX_LENGTH = 120;
export const PRODUCT_VARIANT_OPTION_GROUP_MAX_LENGTH = 120;
export const INVENTORY_STATE_VALUES = [
  "IN_STOCK",
  "LOW_STOCK",
  "OUT_OF_STOCK",
  "PREORDER",
] as const;
