export const ERROR_CODE = [
  "AUTH_REQUIRED",
  "AUTH_FORBIDDEN",
  "EMAIL_NOT_VERIFIED",
  "ADMIN_APPROVAL_REQUIRED",
  "ACCOUNT_SUSPENDED",
  "BRAND_MEMBERSHIP_REQUIRED",
  "VALIDATION_FAILED",
  "RESOURCE_NOT_FOUND",
  "CONFLICT_STATE",
  "INVENTORY_UNAVAILABLE",
  "PAYMENT_REQUIRED",
  "PAYMENT_FAILED",
  "WEBHOOK_INVALID_SIGNATURE",
  "IDEMPOTENCY_CONFLICT",
  "RATE_LIMITED",
  "PROVIDER_UNAVAILABLE",
  "NOT_FOUND",
  "UNKNOWN",
  "VALIDATION",
  "AUTHENTICATION",
  "BAD_REQUEST",
  "UNAUTHORIZED",
  "FORBIDDEN",
  "INTERNAL_SERVER_ERROR",
  "CONFLICT",
  "PAYLOAD_TOO_LARGE",
  "UNSUPPORTED_MEDIA_TYPE",
  "TOO_MANY_REQUESTS",
  "INTERNAL_ERROR",
  "PACKAGE_ERROR",
  "INPUT_ERROR",
  "REQUEST_ERROR",
  "PROCESSING_ERROR",
  "UPLOAD_ERROR",
] as const;

export type ErrorCodeType = (typeof ERROR_CODE)[number];

export const DEFAULT_ERROR_MESSAGE: Record<ErrorCodeType, string> = {
  AUTH_REQUIRED: "Authentication is required.",
  AUTH_FORBIDDEN: "You do not have permission to perform this action.",
  EMAIL_NOT_VERIFIED: "Email verification is required.",
  ADMIN_APPROVAL_REQUIRED: "Admin approval is required.",
  ACCOUNT_SUSPENDED: "Account is suspended.",
  BRAND_MEMBERSHIP_REQUIRED: "Brand membership is required.",
  VALIDATION_FAILED: "The request contains invalid data.",
  RESOURCE_NOT_FOUND: "The requested resource was not found.",
  CONFLICT_STATE: "The request conflicts with the current state.",
  INVENTORY_UNAVAILABLE: "Requested inventory is unavailable.",
  PAYMENT_REQUIRED: "Payment is required.",
  PAYMENT_FAILED: "Payment failed.",
  WEBHOOK_INVALID_SIGNATURE: "Webhook signature is invalid.",
  IDEMPOTENCY_CONFLICT: "The idempotency key conflicts with a previous request.",
  RATE_LIMITED: "Too many requests. Please try again later.",
  PROVIDER_UNAVAILABLE: "A required provider is unavailable. Please try again later.",
  NOT_FOUND: "The requested resource was not found.",
  UNKNOWN: "An unknown error occurred.",
  VALIDATION: "The request contains invalid data.",
  AUTHENTICATION: "Authentication failed.",
  BAD_REQUEST: "The request is invalid.",
  UNAUTHORIZED: "Authentication is required.",
  FORBIDDEN: "You do not have permission to perform this action.",
  INTERNAL_SERVER_ERROR: "An internal server error occurred.",
  CONFLICT: "The request conflicts with the current state.",
  PAYLOAD_TOO_LARGE: "The request payload is too large.",
  UNSUPPORTED_MEDIA_TYPE: "The media type is not supported.",
  TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
  INTERNAL_ERROR: "An internal error occurred.",
  PACKAGE_ERROR: "A package operation failed.",
  INPUT_ERROR: "The input is invalid.",
  REQUEST_ERROR: "The request could not be processed.",
  PROCESSING_ERROR: "Processing failed.",
  UPLOAD_ERROR: "The upload failed.",
};

export class GeneralError<T = unknown> {
  constructor(
    public data: T,
    public code: ErrorCodeType = "UNKNOWN",
    public message: string = DEFAULT_ERROR_MESSAGE[code],
  ) {}
}

export class LogicError<T = unknown> extends GeneralError<T> {}
