export const serverRouteGroups = [
  "admin-auth",
  "customer-auth",
  "customers",
  "owner-governance",
  "brands",
  "categories",
  "products",
  "variants",
  "checkout",
  "payments",
  "webhooks",
  "orders",
  "returns-refunds",
  "assets",
  "audit",
] as const;
